class Proverb
  def initialize
    @proverbs = [["We are Klingons!", "tlhIngan maH!"],
      ["Klingons are born, live as warriors, then die.", "bogh tlhInganpu', SuvwI'pu' moj, Hegh."],
      ["Klingons are born to fight and to conquer.", "SuvmeH 'ej charghmeH bogh tlhInganpu"],
      ["When threatened, fight.", "DabuQlu'DI' yISuv."],
      ["We fight to enrich the spirit.", "qa' wIje'meH maSuv."],
      ["If you are sad, act!", "bI'IQchugh yIvang!"],
      ["Hit them hard and hit them fast.", "tIqIpqu' 'ej nom tIqIp"],
      ["Klingons do not procrastinate.", "lumbe' tlhInganpu"],
      ["If it is in your way, knock it down.", "Dubotchugh yIpummoH"],
      ["To survive, we must expand.", "mataHmeH maSachnIS"],
      ["Klingons are a proud race, and we intend to go on being proud.", "Hem tlhIngan Segh 'ej maHemtaH 'e' wIHech"],
      ["Great deeds, great songs.", "ta'mey Dun, bommey Dun"],
      ["The memory of you sings in my blood.", "bomDI' 'IwwIj qaqaw"],
      ["Brute strength is not the most important asset in a fight.", "Suvlu'taHvIS yapbe' Hos meH"],
      ["Real power is in the heart.", "tIgDaq HoSna' tu'lu"],
      ["There is nothing shameful in falling to a superior enemy.", "Dujeychugh jagh nIv yItuHQo"],
      ["There is no honor in attacking the weak.", "pujwI' HIvlu'chugh quvbe'lu"],
      ["When in doubt, surprise them.", "bISovbejbe'DI' tImer"],
      ["Trust your instincts.", "DujIIj yIvoq"],
      ["Listen to the voice of your blood.", "IwIIj ghogh yIQoy"],
      ["A warrior's blood boils before the fire is hot.", "tujpa' qul pub SuvwI' 'Iw"],
      ["Blood and water don't mix.", "tay'taHbe' 'Iw bIQ je"],
      ["One is always of his tribe.", "reH tay' ghot tuqDaj je"],
      ["A warrior does not let a friend face danger alone.", "nIteb Qob qaD jup 'e' ehaw'be' SuvwI"],
      ["When a warrior goes to a battle, he does not abandon his friends.", "may'Daq jaHDI' SuvwI' juppu'Daj lonbe"],
      ["Klingons do not get sick.", "ropchoHbe' tlhInganpu"],
      ["To understand life, endure pain.", "yIn DayajmeH 'oy' yISIQ"],
      ["Pleasure is nonessential.", "utbe' bel"],
      ["Klingons never bluff.", "not toj tlhInganpu"],
      ["Adhere to virtue honorably.", "batlh ghob yIpab"],
      ["Virtue is the reward.", "pop 'oH ghob'e"],
      ["There is always a chance.", "reH 'eb tu'lu"],
      ["Capture all opportunities.", "Hoch 'ebmey tIjon"],
      ["Honor is more important than life.", "batlh potlh law' yIn potlh puS"],
      ["One does not achieve honor by acting dishonorably.", "batlhHa' vanglu'taHvIS quv chavbe'lu"],
      ["When you insult a Klingon's honor, prepare for trouble.", "tlhIngan quv DatIchDI' Seng yIghuH."],
      ["If you cannot fail, you cannot succeed.", "bIlujlaHbe'chugh bIQaplaHbe"],
      ["A leader must stand alone.", "nIteb SuvnIS DevwI"],
      ["May your enemies run with fear.", "ghIj qet jaghmeyjaj"],
      ["A Klingon does not postpone a matter of honor.", "batlh qelDI' tlhIngan, lumbe"],
      ["It is a good day to die.", "Heghlu'meH QaQ jajvam"],
      ["May you die well.", "batlh bIHeghjaj"],
      ["If you are afraid to die, you have already died.", "blHeghvIpchugh bIHeghpu"],
      ["To die in the line of duty is the hope of every Klingon.", "Qu'Daj ta'taHvIS Hegh 'e' tul Hoch tlhIngan"],
      ["A Klingon warrior is always prepared to fight.", "reh Suvrup tlhIngan SuvwI"],
      ["No Klingon breaks his word.", "not lay'Ha' tlhIngan"],
      ["Focus on but one target.", "wa' DoS neH yIbuS"],
      ["A beard is a symbol of courage.", "toDuj 'oS rol"],
      ["Stop talking! Drink!", "bIjatlh 'e' yImev. yItlhutlh!"],
      ["A warrior fights to the death.", "wej Heghehugh vay', Suvtah SuvwI"],
      ["Klingons do not surrender.", "jeghbe' tlhInganpu"],
      ["A Klingon does not run away from his battles.", "may'meyDajvo' Haw'be' tlhIngan"],
      ["May you die before you are captured.", "Dajonlu'pa' bIHeghjaj"],
      ["Better to die on your feet than live on your knees.", "QamvIS Hegh qaq law' torvIS yIn qaq puS"],
      ["Victory must be earned.", "yay chavlu' 'e' bajnISlu"],
      ["If winning is not important, then why keep score?", "potlhbe'chugh yay qatlh pe'eghlu'?"],
      ["Love is always smelled.", "reH bang larghlu"],
      ["Your father is a part of you always.", "reH DuSIgh vavlI"],
      ["No pain, no gain.", "oy'be'ly'chugh Qapbe'lu"],
      ["Care about your students.", "ghojwI'pu'lI' tISaH"],
      ["We succeed together in a greater whole.", "wa' Dol nIvDaq matay'DI' maQap"],
      ["Have the courage to admit your mistakes.", "QaghmeylIj tIchID, yIyoH"],
      ["Only fools have no fear.", "not qoHpu'e' meH ghIjlu"],
      ["Revenge is a dish which is best served cold.", "bortaS bIr jablu'DI' reH QaQqu' nay"],
      ["Only a fool fights in burning house.", "meQtaHbogh qachDaq Suv qoH neH"],
      ["Even the best blade will rust and grow dull unless it is cared for.", "etlh QorghHa'lu'chugh ragh 'etlh nIvqu' 'ej jejHa'choH"],
      ["What a piece of work is a man! - Hamlet, Act II, Sc. 2", "toH, chovnatlh Doj ghaH tlhIngan'e"]]
  end
  
  def random
    @proverbs.sample
  end
  
  def all
    @proverbs
  end
end

